In [1]:
import numpy as np

In [4]:
5%4

1

# Numpy arrays
Creation and initialization of numpy array

https://numpy.org/doc/stable/reference/routines.array-creation.html

https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

In [2]:
a=np.arange(1,13).reshape((3,4))

In [3]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
a[1,3]

8

In [5]:
np.size(a)

12

In [6]:
b=np.reshape(a,(np.size(a),1))
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [7]:
b.shape

(12, 1)

In [8]:
b.size

12

In [9]:
c=a.flatten()
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
a[:,-1]

array([ 4,  8, 12])

In [11]:
sum(a)/a.shape[0]

array([5., 6., 7., 8.])

In [12]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

To choose the first two rows of the array: `a[0:2,:]`, or `a[0:2]` or simply `a[:2]`.

In [13]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
a[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

To choose the first two columns of the array: `a[:,0:2]`.

In [15]:
a[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

To calculate the transpose of the array:

In [16]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [17]:
(a-1)/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

# Shuffling the array
https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html

In [42]:
a = np.arange(1,81).reshape((8,10))

In [27]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [28]:
a_shuffle=a.copy()
print(a_shuffle)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]
 [71 72 73 74 75 76 77 78 79 80]]


In [36]:
rng = np.random.default_rng()
rng.shuffle(a_shuffle)
print(a_shuffle)

[[61 62 63 64 65 66 67 68 69 70]
 [21 22 23 24 25 26 27 28 29 30]
 [51 52 53 54 55 56 57 58 59 60]
 [ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [41 42 43 44 45 46 47 48 49 50]
 [31 32 33 34 35 36 37 38 39 40]
 [71 72 73 74 75 76 77 78 79 80]]


After shuffling the `a_shuffle`, the original array of `a` remains unchanged.

In [41]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

# Concatenation of arrays & Shuffling dataset

A dataset consists of an array of features and an array of labels `[X, Y]`. 
In order to shuffle the dataset, one first needs to concatenate both arrays in such a way that all fatures and label of each example are in the same direction. 
Otherwise, labels and features are decoupled and shuffling them independently can result in wrong labels to be assigned to each example.
To concatenate the arrays:

In [14]:
import numpy as np

In [23]:
a = np.arange(1,81).reshape((8,10))
b = np.arange(1,9).reshape((8,1))
print(f'a.shape: {a.shape}')
print(f'b.shape: {b.shape}')
#print(f'a:\n{a}')
#print(f'b:\n{b}')

a.shape: (8, 10)
b.shape: (8, 1)


In [20]:
c=np.concatenate((a, b), axis=1)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20,  2],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30,  3],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40,  4],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50,  5],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60,  6],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70,  7],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80,  8]])

Now, if we shuffle the `[X, Y]` dataset, even for many times, each example will stick to its own label:

In [61]:
rng = np.random.default_rng()
c_shuffle=c.copy()
for i in range(10):
    rng.shuffle(c_shuffle)
c_shuffle

array([[51, 52, 53, 54, 55, 56, 57, 58, 59, 60,  6],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50,  5],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20,  2],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40,  4],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30,  3],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80,  8],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1]])

Only now that we are done with shuffling the dataset, we can separate the labels from the dataset. 

In [69]:
x_train = c_shuffle[:,:-1]
y_train = c_shuffle[:,-1]
print(f'x_train:\n{x_train}')
print(f'\ny_train:\n{y_train}')

x_train:
[[51 52 53 54 55 56 57 58 59 60]
 [41 42 43 44 45 46 47 48 49 50]
 [11 12 13 14 15 16 17 18 19 20]
 [31 32 33 34 35 36 37 38 39 40]
 [21 22 23 24 25 26 27 28 29 30]
 [71 72 73 74 75 76 77 78 79 80]
 [61 62 63 64 65 66 67 68 69 70]
 [ 1  2  3  4  5  6  7  8  9 10]]

y_train:
[6 5 2 4 3 8 7 1]


In [74]:
x_train.shape, y_train.shape

((8, 10), (8,))

# Concatenation and shuffling two adjoint 3D arrays

In [13]:
a=np.arange(16).reshape((4,2,2))
ab=np.arange(4).reshape(4)
print(f'a:\n{a}')
print(f'ab:\n{ab}')
#print(a.shape)
#print(a.size)
print('-----------------')
b=a.reshape((a.size,))
#print(b)
#print(b[:5])
#print(b[5:])
#print(b.reshape(a.shape))
print('-----------------')
#c=np.zeros(a.shape)
c=np.arange(16,32).reshape(a.shape)
print(f'c:\n{c}')
print('-----------------')
d=np.concatenate((a, c), axis=2)
print(f'd:\n{d}')
d_shuffle=d.copy()
print('-----------------')
for i in range(10):
    np.random.shuffle(d_shuffle)
print(f'd_shuffle:\n{d_shuffle}')
print(d_shuffle.shape)
print('-----------------')
a_s = d_shuffle[:,:,:a.shape[2]]
c_s = d_shuffle[:,:,c.shape[2]:]
print(f'a_s:\n{a_s}')
print('-----------------')
print(f'c_s:\n{c_s}')
print('-----------------')
print('another way of shuffling using flattened vectors for each row:')
d=np.concatenate((a.reshape((len(a), a.shape[1]*a.shape[2])), c.reshape((len(c), c.shape[1]*c.shape[2]))), axis=1)
print(f'flatten concatenation:\n{d}')
for i in range(10):
    np.random.shuffle(d)
print(f'shuffled flatten concatenation:\n{d}')
a_s = d[:,:a.shape[1]*a.shape[2]].reshape(a.shape)
c_s = d[:,a.shape[1]*a.shape[2]:].reshape(c.shape)
print(f'shuffled reshaped a:\n{a_s}')
print(f'shuffled reshaped c:\n{c_s}')

a:
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
ab:
[0 1 2 3]
-----------------
-----------------
c:
[[[16 17]
  [18 19]]

 [[20 21]
  [22 23]]

 [[24 25]
  [26 27]]

 [[28 29]
  [30 31]]]
-----------------
d:
[[[ 0  1 16 17]
  [ 2  3 18 19]]

 [[ 4  5 20 21]
  [ 6  7 22 23]]

 [[ 8  9 24 25]
  [10 11 26 27]]

 [[12 13 28 29]
  [14 15 30 31]]]
-----------------
d_shuffle:
[[[12 13 28 29]
  [14 15 30 31]]

 [[ 4  5 20 21]
  [ 6  7 22 23]]

 [[ 0  1 16 17]
  [ 2  3 18 19]]

 [[ 8  9 24 25]
  [10 11 26 27]]]
(4, 2, 4)
-----------------
a_s:
[[[12 13]
  [14 15]]

 [[ 4  5]
  [ 6  7]]

 [[ 0  1]
  [ 2  3]]

 [[ 8  9]
  [10 11]]]
-----------------
c_s:
[[[28 29]
  [30 31]]

 [[20 21]
  [22 23]]

 [[16 17]
  [18 19]]

 [[24 25]
  [26 27]]]
-----------------
another way of shuffling using flattened vectors for each row:
flatten concatenation:
[[ 0  1  2  3 16 17 18 19]
 [ 4  5  6  7 20 21 22 23]
 [ 8  9 10 11 24 25 26 27]
 [12 13 14 15 28 29 30 31]]
s

# Difference between a vector and a matrix of nx1 shape
https://stackoverflow.com/questions/39549331/reshape-numpy-n-vector-to-n-1-vector & https://stackoverflow.com/questions/22998318/from-n-to-n-1-numpy-arrays-and-viceversa

In [3]:
import numpy as np

In the following, `a` is a vector:

In [9]:
a=np.ones(5)
print(a)
print(a.shape)

[1. 1. 1. 1. 1.]
(5,)


and `b` is a 2d array:

In [11]:
b=np.ones((5,1))
print(b)
print(b.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(5, 1)


Now, let's say we want to compare `a` and `b`. We cannot just use `a==b`, since it returns a 5x5 matrix:

In [12]:
a==b

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

Instead, we need to first convert the 2d array of `b` to a vector format, and then compare it with `a`:

In [16]:
b_vec = b.reshape(len(b),)
print(b_vec)

[1. 1. 1. 1. 1.]


In [18]:
a==b_vec

array([ True,  True,  True,  True,  True])

# Normalizing a 2d array
Let's say we have a 2d array like `a` and we want to normalize each column to have a zero mean and a unit standard deviation.

In [1]:
import numpy as np

In [4]:
a = np.arange(50).reshape(10,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [14]:
mu0 = a.mean(0)
mu1 = a.mean(1)
print(mu0.shape)
print(mu0)
print(mu1.shape)
print(mu1)

(5,)
[22.5 23.5 24.5 25.5 26.5]
(10,)
[ 2.  7. 12. 17. 22. 27. 32. 37. 42. 47.]


In [15]:
sigma0 = a.std(0)
sigma1 = a.std(1)
print(sigma0.shape)
print(sigma0)
print(sigma1.shape)
print(sigma1)

(5,)
[14.36140662 14.36140662 14.36140662 14.36140662 14.36140662]
(10,)
[1.41421356 1.41421356 1.41421356 1.41421356 1.41421356 1.41421356
 1.41421356 1.41421356 1.41421356 1.41421356]


In [17]:
b = (a-mu0)/sigma0
print(b)

[[-1.5666989  -1.5666989  -1.5666989  -1.5666989  -1.5666989 ]
 [-1.21854359 -1.21854359 -1.21854359 -1.21854359 -1.21854359]
 [-0.87038828 -0.87038828 -0.87038828 -0.87038828 -0.87038828]
 [-0.52223297 -0.52223297 -0.52223297 -0.52223297 -0.52223297]
 [-0.17407766 -0.17407766 -0.17407766 -0.17407766 -0.17407766]
 [ 0.17407766  0.17407766  0.17407766  0.17407766  0.17407766]
 [ 0.52223297  0.52223297  0.52223297  0.52223297  0.52223297]
 [ 0.87038828  0.87038828  0.87038828  0.87038828  0.87038828]
 [ 1.21854359  1.21854359  1.21854359  1.21854359  1.21854359]
 [ 1.5666989   1.5666989   1.5666989   1.5666989   1.5666989 ]]


# 3D array

In [1]:
import numpy as np

In [6]:
a=np.arange(36).reshape((4,3,3))
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [12]:
a[1:,1:,1:]

array([[[13, 14],
        [16, 17]],

       [[22, 23],
        [25, 26]],

       [[31, 32],
        [34, 35]]])

# range

In [6]:
x=range(10,4,-1)
for n in x:
    print(n)

10
9
8
7
6
5


# Appending to an existing array

In [7]:
import numpy as np

In [11]:
a=np.arange(5).reshape((1,5))
b=np.arange(1,10,2).reshape((1,5))
print(a)
print(b)

[[0 1 2 3 4]]
[[1 3 5 7 9]]


In [18]:
c=np.append(a,b,axis=0)
print(c.shape)
print(c)

(2, 5)
[[0 1 2 3 4]
 [1 3 5 7 9]]


In [23]:
for i in range(5):
    c=np.append(c,a,axis=0)
print(c.shape)
print(c)

(17, 5)
[[0 1 2 3 4]
 [1 3 5 7 9]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [37]:
d=np.array([])
print(d.shape)
print(d.size)

(0,)
0


In [38]:
if d.size==0:
    d=np.copy(a)
else:
    d=np.append(d,a,axis=0)
print(d.shape)
print(d.size)
print(d)

(1, 5)
5
[[0 1 2 3 4]]


In [ ]:
for i in range(5):
    d=np.append(d,a,axis=0)
print(c.shape)
print(c)