In [1]:
import numpy as np

# Numpy arrays
Creation and initialization of numpy array

https://numpy.org/doc/stable/reference/routines.array-creation.html

https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

In [2]:
a=np.arange(1,13).reshape((3,4))

In [3]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
a[1,3]

8

In [5]:
np.size(a)

12

In [6]:
b=np.reshape(a,(np.size(a),1))
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [7]:
b.shape

(12, 1)

In [8]:
b.size

12

In [9]:
c=a.flatten()
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
a[:,-1]

array([ 4,  8, 12])

In [11]:
sum(a)/a.shape[0]

array([5., 6., 7., 8.])

In [12]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

To choose the first two rows of the array: `a[0:2,:]`, or `a[0:2]` or simply `a[:2]`.

In [13]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
a[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

To choose the first two columns of the array: `a[:,0:2]`.

In [15]:
a[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

To calculate the transpose of the array:

In [16]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [17]:
(a-1)/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])